# Generated by Django 3.1.5 on 2021-01-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcuser',
            table='fastcampus_fcuser',
        ),
    ]
